import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Navigation } from './_Components/Navigation/Navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
  
      <body className={inter.className}>
      <Navigation />
        {children}
        <footer className='bg-stone-950 min-h-[15vh]  border-t-[1px] border-stone-700 flex items-center justify-center'>
        <span className='text-stone-300'>Designed and Developed by Samuel Baran </span>
        </footer>
        </body>
    </html>
  )
}
